import type { AssistantMessage } from "assistant-stream";
import type { CaseDigest } from "../lib/caseDigestDocx";
import type { AgentExecution } from "../pyodide/types";
import type { RetrievalHit } from "./retrieval";

export interface ChatMessageBase {
  id: string;
  at: string;
}

export type PersistedChatMessage =
  | (ChatMessageBase & { role: "assistant"; kind: "welcome" })
  | (ChatMessageBase & { role: "assistant"; kind: "nudge" })
  | (ChatMessageBase & { role: "assistant"; kind: "error"; text: string })
  | (ChatMessageBase & { role: "user"; kind: "attachment"; fileName: string })
  | (ChatMessageBase & { role: "user"; kind: "question"; text: string })
  | (ChatMessageBase & {
      role: "assistant";
      kind: "parse-summary";
      fileName: string;
      pageCount: number;
      nodeCount: number;
      ms: number;
      pdfType: string;
    })
  | (ChatMessageBase & { role: "assistant"; kind: "references"; query: string; refs: RetrievalHit[] })
  | (ChatMessageBase & {
      role: "assistant";
      kind: "agent-answer";
      markdown: string;
      refs: RetrievalHit[];
      execution: AgentExecution;
    })
  | (ChatMessageBase & {
      role: "assistant";
      kind: "digest";
      markdown: string;
      digest: CaseDigest;
      refs: RetrievalHit[];
      execution: AgentExecution;
      docxFileId: string;
      docxFileName: string;
    });

export interface AgentStreamMessage extends ChatMessageBase {
  role: "assistant";
  kind: "agent-stream";
  markdown: string;
  assistant: AssistantMessage;
  execution: AgentExecution;
}

/** Runtime-only fields are deliberately excluded before a message reaches IndexedDB. */
export type ChatMessage =
  | Exclude<PersistedChatMessage, { kind: "agent-answer" | "digest" }>
  | (Extract<PersistedChatMessage, { kind: "agent-answer" }> & { assistant?: AssistantMessage })
  | (Extract<PersistedChatMessage, { kind: "digest" }> & { docxUrl?: string; docxBlob?: Blob })
  | AgentStreamMessage;

export interface DigestSession {
  id: string;
  title: string;
  documentId: string | null;
  createdAt: string;
  updatedAt: string;
  messages: PersistedChatMessage[];
}

export interface DigestSessionSummary {
  id: string;
  title: string;
  documentId: string | null;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
}

/** A DOCX generated by a digest session and retained for preview/download. */
export interface DigestSessionAsset {
  id: string;
  sessionId: string;
  fileName: string;
  mimeType: string;
  blob: Blob;
}

export const DEFAULT_VISIBLE_DIGEST_SESSIONS = 5;

export function serializeChatMessage(message: ChatMessage): PersistedChatMessage | null {
  if (message.kind === "agent-stream") return null;
  if (message.kind === "agent-answer") {
    return {
      id: message.id,
      at: message.at,
      role: message.role,
      kind: message.kind,
      markdown: message.markdown,
      refs: message.refs,
      execution: message.execution,
    };
  }
  if (message.kind === "digest") {
    return {
      id: message.id,
      at: message.at,
      role: message.role,
      kind: message.kind,
      markdown: message.markdown,
      digest: message.digest,
      refs: message.refs,
      execution: message.execution,
      docxFileId: message.docxFileId,
      docxFileName: message.docxFileName,
    };
  }
  return message;
}

export function summarizeDigestSession(session: DigestSession): DigestSessionSummary {
  return {
    id: session.id,
    title: session.title,
    documentId: session.documentId,
    createdAt: session.createdAt,
    updatedAt: session.updatedAt,
    messageCount: session.messages.length,
  };
}

export function sortDigestSessionSummaries(sessions: DigestSessionSummary[]): DigestSessionSummary[] {
  return [...sessions].sort((left, right) =>
    right.updatedAt.localeCompare(left.updatedAt)
    || right.createdAt.localeCompare(left.createdAt)
    || left.id.localeCompare(right.id),
  );
}

export function visibleDigestSessions(sessions: DigestSessionSummary[], expanded: boolean): DigestSessionSummary[] {
  const ordered = sortDigestSessionSummaries(sessions);
  return expanded ? ordered : ordered.slice(0, DEFAULT_VISIBLE_DIGEST_SESSIONS);
}

export function hasOlderDigestSessions(sessions: DigestSessionSummary[]): boolean {
  return sessions.length > DEFAULT_VISIBLE_DIGEST_SESSIONS;
}
