"""Document-tree models and navigation helpers for the agent tools."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


DocumentNodeKind = Literal["document", "section", "block"]


class DocumentNode(BaseModel):
    """Serializable node shape produced by the TypeScript PDF context tree."""

    model_config = ConfigDict(extra="forbid", strict=True)

    id: str
    kind: DocumentNodeKind
    label: str
    section: str
    page: int | None = None
    text: str | None = None
    children: list[DocumentNode] = Field(default_factory=list)


class DocumentReference(BaseModel):
    """A source node reference that can be highlighted by the browser UI."""

    model_config = ConfigDict(extra="forbid", strict=True)

    node_id: str
    kind: DocumentNodeKind
    label: str
    section: str
    page: int | None
    snippet: str


class NavigationEntry(BaseModel):
    """One child exposed by document navigation with its source reference."""

    model_config = ConfigDict(extra="forbid", strict=True)

    node_id: str
    kind: DocumentNodeKind
    label: str
    section: str
    page: int | None
    text: str | None = None
    child_count: int = 0


class NavigationResult(BaseModel):
    """A document outline or the contents of one selected section."""

    model_config = ConfigDict(extra="forbid", strict=True)

    requested_section: str | None
    section: str | None
    page: int | None
    entries: list[NavigationEntry] = Field(default_factory=list)
    error: str | None = None


def flatten_tree(root: DocumentNode) -> list[DocumentNode]:
    """Return all nodes in stable depth-first order."""
    nodes: list[DocumentNode] = []

    def visit(node: DocumentNode) -> None:
        nodes.append(node)
        for child in node.children:
            visit(child)

    visit(root)
    return nodes


def reference_for_node(node: DocumentNode) -> DocumentReference:
    """Convert a tree node into the compact source reference sent to the UI."""
    source = (node.text or node.label).strip()
    if len(source) > 180:
        source = f"{source[:177]}..."
    return DocumentReference(
        node_id=node.id,
        kind=node.kind,
        label=node.label,
        section=node.section,
        page=node.page,
        snippet=source,
    )


def find_section(root: DocumentNode, section_path: str) -> DocumentNode | None:
    """Find a section by the path generated by ``buildContextTree``."""
    normalized_path = " ".join(section_path.split()).strip()
    if not normalized_path:
        return None

    for node in flatten_tree(root):
        if node.kind == "document" and node.section == normalized_path:
            return node
        if node.kind == "section" and node.section == normalized_path:
            return node
    return None


def _navigation_entry(node: DocumentNode) -> NavigationEntry:
    return NavigationEntry(
        node_id=node.id,
        kind=node.kind,
        label=node.label,
        section=node.section,
        page=node.page,
        text=node.text if node.kind == "block" else None,
        child_count=len(node.children),
    )


def navigate_document_tree(root: DocumentNode, section_path: str | None = None) -> NavigationResult:
    """Return the root outline or the immediate contents of a document section."""
    if section_path is None:
        target = root
    else:
        selected = find_section(root, section_path)
        if selected is None:
            return NavigationResult(
                requested_section=section_path,
                section=None,
                page=None,
                error=f"Section not found: {section_path}",
            )
        target = selected

    return NavigationResult(
        requested_section=section_path,
        section=target.section,
        page=target.page,
        entries=[_navigation_entry(child) for child in target.children],
    )
